package com.clinica.entity;
// Generated 28/11/2019 01:53:43 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Alumno generated by hbm2java
 */
public class Alumno  implements java.io.Serializable {


     private String matricula;
     private Carrera carrera;
     private Semestre semestre;
     private String nombre;
     private String grupo;
     private Date fechacreacion;
     private Date fechaactualizacion;
     private Date fechaeliminacion;
     private Set registros = new HashSet(0);

    public Alumno() {
    }

	
    public Alumno(String matricula, Carrera carrera, Semestre semestre, String nombre, String grupo, Date fechacreacion) {
        this.matricula = matricula;
        this.carrera = carrera;
        this.semestre = semestre;
        this.nombre = nombre;
        this.grupo = grupo;
        this.fechacreacion = fechacreacion;
    }
    public Alumno(String matricula, Carrera carrera, Semestre semestre, String nombre, String grupo, Date fechacreacion, Date fechaactualizacion, Date fechaeliminacion, Set registros) {
       this.matricula = matricula;
       this.carrera = carrera;
       this.semestre = semestre;
       this.nombre = nombre;
       this.grupo = grupo;
       this.fechacreacion = fechacreacion;
       this.fechaactualizacion = fechaactualizacion;
       this.fechaeliminacion = fechaeliminacion;
       this.registros = registros;
    }
   
    public String getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(String matricula) {
        this.matricula = matricula;
    }
    public Carrera getCarrera() {
        return this.carrera;
    }
    
    public void setCarrera(Carrera carrera) {
        this.carrera = carrera;
    }
    public Semestre getSemestre() {
        return this.semestre;
    }
    
    public void setSemestre(Semestre semestre) {
        this.semestre = semestre;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(String grupo) {
        this.grupo = grupo;
    }
    public Date getFechacreacion() {
        return this.fechacreacion;
    }
    
    public void setFechacreacion(Date fechacreacion) {
        this.fechacreacion = fechacreacion;
    }
    public Date getFechaactualizacion() {
        return this.fechaactualizacion;
    }
    
    public void setFechaactualizacion(Date fechaactualizacion) {
        this.fechaactualizacion = fechaactualizacion;
    }
    public Date getFechaeliminacion() {
        return this.fechaeliminacion;
    }
    
    public void setFechaeliminacion(Date fechaeliminacion) {
        this.fechaeliminacion = fechaeliminacion;
    }
    public Set getRegistros() {
        return this.registros;
    }
    
    public void setRegistros(Set registros) {
        this.registros = registros;
    }




}


