package com.clinica.entity;
// Generated 28/11/2019 01:53:43 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Carrera generated by hbm2java
 */
public class Carrera  implements java.io.Serializable {


     private String codigo;
     private String nombre;
     private Set alumnos = new HashSet(0);
     private Set practicas = new HashSet(0);

    public Carrera() {
    }

	
    public Carrera(String codigo, String nombre) {
        this.codigo = codigo;
        this.nombre = nombre;
    }
    public Carrera(String codigo, String nombre, Set alumnos, Set practicas) {
       this.codigo = codigo;
       this.nombre = nombre;
       this.alumnos = alumnos;
       this.practicas = practicas;
    }
   
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getAlumnos() {
        return this.alumnos;
    }
    
    public void setAlumnos(Set alumnos) {
        this.alumnos = alumnos;
    }
    public Set getPracticas() {
        return this.practicas;
    }
    
    public void setPracticas(Set practicas) {
        this.practicas = practicas;
    }




}


