package com.clinica.entity;
// Generated 28/11/2019 01:53:43 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Registro generated by hbm2java
 */
public class Registro  implements java.io.Serializable {


     private long idregistro;
     private Alumno alumno;
     private Practica practica;
     private Date horaentrada;
     private Date horasalida;
     private Date fecha;
     private String sustituye;
     private String estado;
     private String comentario;

    public Registro() {
    }

	
    public Registro(long idregistro, Alumno alumno, Practica practica, String sustituye, String estado) {
        this.idregistro = idregistro;
        this.alumno = alumno;
        this.practica = practica;
        this.sustituye = sustituye;
        this.estado = estado;
    }
    public Registro(long idregistro, Alumno alumno, Practica practica, Date horaentrada, Date horasalida, Date fecha, String sustituye, String estado, String comentario) {
       this.idregistro = idregistro;
       this.alumno = alumno;
       this.practica = practica;
       this.horaentrada = horaentrada;
       this.horasalida = horasalida;
       this.fecha = fecha;
       this.sustituye = sustituye;
       this.estado = estado;
       this.comentario = comentario;
    }
   
    public long getIdregistro() {
        return this.idregistro;
    }
    
    public void setIdregistro(long idregistro) {
        this.idregistro = idregistro;
    }
    public Alumno getAlumno() {
        return this.alumno;
    }
    
    public void setAlumno(Alumno alumno) {
        this.alumno = alumno;
    }
    public Practica getPractica() {
        return this.practica;
    }
    
    public void setPractica(Practica practica) {
        this.practica = practica;
    }
    public Date getHoraentrada() {
        return this.horaentrada;
    }
    
    public void setHoraentrada(Date horaentrada) {
        this.horaentrada = horaentrada;
    }
    public Date getHorasalida() {
        return this.horasalida;
    }
    
    public void setHorasalida(Date horasalida) {
        this.horasalida = horasalida;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getSustituye() {
        return this.sustituye;
    }
    
    public void setSustituye(String sustituye) {
        this.sustituye = sustituye;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }




}


