package com.clinica.entity;
// Generated 26/11/2019 07:51:05 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Reservacion generated by hbm2java
 */
public class Reservacion  implements java.io.Serializable {


     private long idreservacion;
     private Date fechainicio;
     private Date fechafin;
     private String area;
     private String responsablearea;
     private String practica;
     private String responsablepractica;

    public Reservacion() {
    }

    public Reservacion(long idreservacion, Date fechainicio, Date fechafin, String area, String responsablearea, String practica, String responsablepractica) {
       this.idreservacion = idreservacion;
       this.fechainicio = fechainicio;
       this.fechafin = fechafin;
       this.area = area;
       this.responsablearea = responsablearea;
       this.practica = practica;
       this.responsablepractica = responsablepractica;
    }
   
    public long getIdreservacion() {
        return this.idreservacion;
    }
    
    public void setIdreservacion(long idreservacion) {
        this.idreservacion = idreservacion;
    }
    public Date getFechainicio() {
        return this.fechainicio;
    }
    
    public void setFechainicio(Date fechainicio) {
        this.fechainicio = fechainicio;
    }
    public Date getFechafin() {
        return this.fechafin;
    }
    
    public void setFechafin(Date fechafin) {
        this.fechafin = fechafin;
    }
    public String getArea() {
        return this.area;
    }
    
    public void setArea(String area) {
        this.area = area;
    }
    public String getResponsablearea() {
        return this.responsablearea;
    }
    
    public void setResponsablearea(String responsablearea) {
        this.responsablearea = responsablearea;
    }
    public String getPractica() {
        return this.practica;
    }
    
    public void setPractica(String practica) {
        this.practica = practica;
    }
    public String getResponsablepractica() {
        return this.responsablepractica;
    }
    
    public void setResponsablepractica(String responsablepractica) {
        this.responsablepractica = responsablepractica;
    }




}


